obj-m := isdbt.o

ccflags-y := -I$(TOP)/vendor/fci/dtvdriver/sdk/inc
isdbt-y := bbm.o fc8350.o fc8350_bb.o fc8350_i2c.o fc8350_isr.o fc8350_spi.o fc8350_tun.o fc8350_tun_table.o fci_hal.o fci_hpi.o fci_oal.o fci_ringbuffer.o fci_tun.o
